sudo: required
services:
  - docker

before_install:
  - docker build - jsammut1976/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jsammut1976/react-test npm test

after_success:
  - docker build -t jsammut1976/multi-client ./client
  - docker build -t jsammut1976/multi-nginx ./nginx
  - docker build -t jsammut1976/multi-server ./server
  - docker build -t jsammut1976/multi-worker ./worker

  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdi
  # take those images and push them to docker hub
  - docker push jsammut1976/multi-client
  - docker push jsammut1976/multi-nginx
  - docker push jsammut1976/multi-server
  - docker push jsammut1976/multi-worker
