sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jsammut1976/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jsammut1976/react-test npm test

after_success:
  - docker build -t jsammut/multi-client ./client
  - docker build -t jsammut/multi-nginx ./nginx
  - docker build -t jsammut/multi-server ./server
  - docker build -t jsammut/multi-worker ./worker

  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push jsammut/multi-client
  - docker push jsammut/multi-nginx
  - docker push jsammut/multi-server
  - docker push jsammut/multi-worker
# test comment
